spring:
  application:
    name: movie-fun-app

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

albums:
  url: //album-service/albums
movies:
  url: //movie-service/movies

s3:
  accessKey: <access key id>
  secretKey: <secret access key>
  bucketName: <name of the bucket>
